name: Build with MPLAB v6.05 and XC8 v2.40
description: This action builds a MPLAB X / XC8 project in a Linux container.
branding:
  icon: package
  color: gray-dark
inputs:
  project:
    description: Project folder location
    required: true
  configuration:
    description: Configuration to build
    required: true
    default: default
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project }}
    - ${{ inputs.configuration }}
